import './globals.css'
import { Inter } from 'next/font/google'
import {HeaderContextProvider } from  "../context/headerContext"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Blog Posts',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderContextProvider>
          {children}
        </HeaderContextProvider>
      </body>
    </html>
  )
}
